const items = [
  {
    id: 1,
    title: 'Bread Omlette',
    category: 'Breakfast',
    price: 40,
    img: '/images/breakfast-1.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minus consequatur',
  },
  {
    id: 2,
    title: 'Chicken Biriyani',
    category: 'Lunch',
    price: 90,
    img: '/images/lunch-2.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minusi',
  },
  {
    id: 3,
    title: 'Strawberry Delight',
    category: 'Juices',
    price: 60,
    img: '/images/drinks-1.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minusi',
  },
  {
    id: 4,
    title: 'Lassi',
    category: 'Juices',
    price: 100,
    img: '/images/drinks-2.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minusi',
  },
  {
    id: 5,
    title: 'Pane Carasare',
    category: 'breakfast',
    price: 120,
    img: '/images/lunch-1.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minusi',
  },
  {
    id: 6,
    title: 'Summer Fighter',
    category: 'shakes',
    price: 80,
    img: '/images/drinks-3.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minusi',
  },
  {
    id: 7,
    title: 'Muscle Builder Meal',
    category: 'lunch',
    price: 70,
    img: '/images/lunch-3.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minusi',
  },
  {
    id: 8,
    title: 'American Classic',
    category: 'lunch',
    price: 90,
    img: '/images/breakfast-4.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minusi',
  },
  {
    id: 9,
    title: 'Waffle',
    category: 'lunch',
    price: 65,
    img: '/images/breakfast-2.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minusi',
  },
  {
    id: 10,
    title: 'Day Starter',
    category: 'lunch',
    price: 65,
    img: '/images/breakfast-3.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis, minusi',
  }
]

export default items
